debug: true

app:
    name: Werewolf of Deepseeks
    author: Churk_Ben
    version: 2.0

# 本地服务器配置
web:
    enable: false
    host: 127.0.0.1
    port: 5000

# 玩家配置
players:
    - name: Kimi-k2-0905
      human: false
      model: moonshot/kimi-k2-0905-preview

    - name: Gemini-2.5-flash
      human: false
      model: gemini/gemini-2.5-flash

    - name: Kimi-thinking
      human: false
      model: moonshot/kimi-thinking-preview

    - name: Deepseek-v3.1-thinking
      human: false
      model: deepseek/deepseek-reasoner

    - name: Deepseek-v3.1
      human: false
      model: deepseek/deepseek-chat

    - name: Gemini-2.5-Pro
      human: false
      model: gemini/gemini-2.5-pro
